server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://ewm_postgres:5432/ewmdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info

stat:
  server:
    url: ${STAT_SERVER_URL:http://statserver:9090}
