services:
  stats-db:
    image: postgres:15-alpine
    platform: linux/arm64
    container_name: stats_postgres
    environment:
      POSTGRES_DB: statsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - stats_data:/var/lib/postgresql/data

  stats-server:
    build: ./stat-server
    container_name: stat_server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/statsdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SERVER_PORT: 9090
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    command: ["java", "-jar", "app.jar"]

volumes:
  stats_data:
